version: "3.9"

services:
  postgres:
    container_name: postgres-tags
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: "/data/postgres"
    networks:
      - mod-tags-local

  pgadmin:
    container_name: pgadmin-tags
    image: dpage/pgadmin4:6.7
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - mod-tags-local

  mod-tags:
    container_name: mod-tags
    image: dev.folio/mod-tags
    build:
      context: ..\
      dockerfile: Dockerfile
    ports:
      - "9138:8081"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      ENV: ${ENV}
      DB_USERNAME: ${DB_USERNAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      JAVA_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
    depends_on:
      - "postgres"
    networks:
      - mod-tags-local

networks:
  mod-tags-local:
    driver: "bridge"

volumes:
  pgadmin-data:
    driver: "local"
  postgres-data:
    driver: "local"
