#%RAML 0.8

title: Notes API
baseUri: https://github.com/folio-org/mod-tags
version: v1

documentation:
  - title: mod-tags API
    content: This documents the API calls that can be made to post tags that can be attached to various objects

schemas:
  - tag.json: !include tag.json
  - tagsCollection: !include tagsCollection.json
  - errors: !include raml-util/schemas/errors.schema
  - error.schema: !include raml-util/schemas/error.schema
  - parameters.schema: !include raml-util/schemas/parameters.schema
  - raml-util/schemas/metadata.schema: !include raml-util/schemas/metadata.schema

traits:
  - validate: !include raml-util/traits/validation.raml
  - secured: !include raml-util/traits/auth.raml
  - language: !include raml-util/traits/language.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/tags:
  displayName: Tags
  description: Tags that can be attached to various objects
  type:
    collection:
      schemaCollection: tagsCollection
      schemaItem: tag.json
      exampleCollection: !include examples/tagsCollection.sample
      exampleItem: !include examples/tag.sample

  post:
    is: [
      validate
    ]
  get:
    is: [
      searchable: {description: "with valid searchable fields: for example label=foo", example: "label=foo"},
      pageable,
      validate
    ]
  /{id}:
    displayName: Tags
    description: Get, Delete or Update a specific tag
    type:
      collection-item:
        schema: tag.json
        exampleItem: !include examples/tag.sample
    put:
      is: [validate]
